config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'report_pdf' => 'posts#report_pdf'
  root "home#index"
  # controller :home do
  #   resources :home
  #   get 'convert'
  #   get 'pdf'
  # end
  controller :students do
    resources :students
    get :convert
    get :pdf
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def pdf
  	# this method will be called by Dhalang
  end

  def convert
  	_url = request.base_url + pdf_path
  	_pdf = Dhalang::PDF.get_from_url(_url)
  	_file_name = "Report" 
        File.open("#{Rails.root}/public/#{_file_name}.pdf", "w+b") << _pdf
	redirect_to "/#{_file_name}.pdf"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def report_pdf
    @report_pdf = Post.all
    respond_to do |format|
      format.html
      format.pdf do
        render template: "posts/report_pdf.html.erb",
          pdf: "Posts: #{@report_pdf.count}",
          layout: "pdf",
          window_status: "FLAG_FOR_PDF"
      end
    end
  end

  def index
    @posts = Post.all.order("updated_at DESC")
    respond_to do |format|
      format.html
      format.pdf do
        render template: "posts/index.html.erb",
          pdf: "Posts: #{@posts.count}"
      end
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  def pdf
    @product = Post.all
    respond_to do |format|
      format.html
      format.pdf do
        render template: "products/pdf.html.erb",
          pdf: "Product: #{@product.count}"
      end
    end
  end

  def convert
    _url = request.base_url + pdf_path
    _pdf = Dhalang::PDF.get_from_url(_url)
    _file_name = "Report" 
        File.open("#{Rails.root}/public/#{_file_name}.pdf", "w+b") << _pdf
  redirect_to "/#{_file_name}.pdf"
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :body)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  def pdf
     @students = Student.all
    respond_to do |format|
      format.html
      format.pdf do
        render template: "students/index.html.erb",
          pdf: "Students: #{@pdf.count}"
      end
    end
  end

  def convert
    @students = Student.all
    _url = request.base_url + pdf_path
    _pdf = Dhalang::PDF.get_from_url(_url)
    _file_name = "Report" 
        File.open("#{Rails.root}/public/#{_file_name}.pdf", "w+b") << _pdf
  redirect_to "/#{_file_name}.pdf"
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/_form.html.erb
<%= form_with(model: home) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="" style="padding: 30px; margin: auto; text-align: center;">
	<%= link_to "CONVERT TO PDF", convert_path, target: "_blank" %>
</div>
<canvas id="sample"></canvas>
<script type="text/javascript">
	<%= render "home/partials/main.js"%>
</script>

app/views/home/partials/_main.js.erb
var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
var config = {
	type: 'line',
	data: {
		labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
		datasets: [{
			label: 'My First dataset',
			borderColor: "#C6C22F",
			backgroundColor: "#C6C22F",
			data: [
				44,
				55,
				20,
				21,
				89,
				52,
				33
			],
		}, {
			label: 'My Second dataset',
			borderColor: "#4DAA33",
			backgroundColor: "#4DAA33",
			data: [
				24,
				55,
				60,
				11,
				89,
				82,
				73
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#C559A5",
			backgroundColor: "#C559A5",
			data: [
				41,
				55,
				94,
				61,
				81,
				52,
				30
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#45CCB7",
			backgroundColor: "#45CCB7",
			data: [
				23,77,58,43,45,75,32
			],
		}]
	},
	options: {
		responsive: true,
		title: {
			display: true,
			text: 'Chart.js Line Chart - Stacked Area'
		},
		tooltips: {
			mode: 'index',
		},
		hover: {
			mode: 'index'
		},
		scales: {
			xAxes: [{
				scaleLabel: {
					display: true,
					labelString: 'Month'
				}
			}],
			yAxes: [{
				stacked: true,
				scaleLabel: {
					display: true,
					labelString: 'Value'
				}
			}]
		}
	}
};

window.onload = function() {
	var ctx = document.getElementById('sample').getContext('2d');
	window.myLine = new Chart(ctx, config);
};

app/views/home/pdf.html.erb
<canvas id="sample"></canvas>

<script type="text/javascript">
	<%= render "home/partials/main.js"%>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
    <%= yield :google_chart_scripts %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= wicked_pdf_stylesheet_link_tag 'application' %>
   
    <!-- This is not working in production compiled assets. -->
    <!-- <%= wicked_pdf_javascript_include_tag 'pdf' %> -->
    <%= javascript_include_tag wicked_pdf_asset_base64('pdf') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Posts</h1>
<%= pie_chart Post.group(:title).count %>

<%= link_to "Download PDF", report_pdf_path(format: :pdf), class: "btn btn-sm btn-default", target: "_blank" %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Body</th>
      <th>StartDate</th>
      <th>EndDate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.created_at%></td>
        <td><%= post.updated_at%></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/partials/_main.js.erb
var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
var config = {
	type: 'line',
	data: {
		labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
		datasets: [{
			label: 'My First dataset',
			borderColor: "#C6C22F",
			backgroundColor: "#C6C22F",
			data: [
				44,
				55,
				20,
				21,
				89,
				52,
				33
			],
		}, {
			label: 'My Second dataset',
			borderColor: "#4DAA33",
			backgroundColor: "#4DAA33",
			data: [
				24,
				55,
				60,
				11,
				89,
				82,
				73
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#C559A5",
			backgroundColor: "#C559A5",
			data: [
				41,
				55,
				94,
				61,
				81,
				52,
				30
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#45CCB7",
			backgroundColor: "#45CCB7",
			data: [
				23,77,58,43,45,75,32
			],
		}]
	},
	options: {
		responsive: true,
		title: {
			display: true,
			text: 'Chart.js Line Chart - Stacked Area'
		},
		tooltips: {
			mode: 'index',
		},
		hover: {
			mode: 'index'
		},
		scales: {
			xAxes: [{
				scaleLabel: {
					display: true,
					labelString: 'Month'
				}
			}],
			yAxes: [{
				stacked: true,
				scaleLabel: {
					display: true,
					labelString: 'Value'
				}
			}]
		}
	}
};

window.onload = function() {
	var ctx = document.getElementById('sample').getContext('2d');
	window.myLine = new Chart(ctx, config);
};

app/views/posts/report_pdf.html.erb
<%#= javascript_include_tag "https://www.google.com/jsapi" %>
<%#= wicked_pdf_javascript_include_tag "chartkick" %>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://www.gstatic.com/charts/loader.js"></script>
<script>
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawChart);
  ...
</script>
<%= wicked_pdf_javascript_include_tag "application", "chartkick" %>
<%= pie_chart Post.group(:title).count %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>

  <tbody>
    <% @report_pdf.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= link_to "Download PDF", pdf_path(format: :pdf), class: "btn btn-sm btn-default", target: "_blank" %>
<div class="" style="padding: 30px; margin: auto; text-align: center;">
  <%= link_to "CONVERT TO PDF", convert_path, target: "_blank" %>
</div>
<canvas id="sample"></canvas>
<script type="text/javascript">
  <%= render "home/partials/main.js"%>
</script>
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.body %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/partials/_main.js.erb
var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
var config = {
	type: 'line',
	data: {
		labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
		datasets: [{
			label: 'My First dataset',
			borderColor: "#C6C22F",
			backgroundColor: "#C6C22F",
			data: [
				44,
				55,
				20,
				21,
				89,
				52,
				33
			],
		}, {
			label: 'My Second dataset',
			borderColor: "#4DAA33",
			backgroundColor: "#4DAA33",
			data: [
				24,
				55,
				60,
				11,
				89,
				82,
				73
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#C559A5",
			backgroundColor: "#C559A5",
			data: [
				41,
				55,
				94,
				61,
				81,
				52,
				30
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#45CCB7",
			backgroundColor: "#45CCB7",
			data: [
				23,77,58,43,45,75,32
			],
		}]
	},
	options: {
		responsive: true,
		title: {
			display: true,
			text: 'Chart.js Line Chart - Stacked Area'
		},
		tooltips: {
			mode: 'index',
		},
		hover: {
			mode: 'index'
		},
		scales: {
			xAxes: [{
				scaleLabel: {
					display: true,
					labelString: 'Month'
				}
			}],
			yAxes: [{
				stacked: true,
				scaleLabel: {
					display: true,
					labelString: 'Value'
				}
			}]
		}
	}
};

window.onload = function() {
	var ctx = document.getElementById('sample').getContext('2d');
	window.myLine = new Chart(ctx, config);
};

app/views/products/pdf.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @product.body %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<canvas id="sample"></canvas>
<script type="text/javascript">

</script>
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.created_at %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "PDF", convert_path(format: :pdf), class: "btn btn-sm btn-default", target: "_blank" %>
<%= link_to 'New Student', new_student_path %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<%= wicked_pdf_javascript_include_tag 'jquery-1.6.2.min', 'dr_statistics/highcharts' %>
<script>

  $(function () {
     $('#container').highcharts({
      chart: {
        type: 'column'
      },
      first_name: {
        text: 'Monthly Average Rainfall'
      },
      last_name: {
        text: 'Source: WorldClimate.com'
      },
      xAxis: {
        students: [
          'first_name',
          'last_name'
          
        ]
      },
      yAxis: {
        min: 0,
        title: {
          text: 'No of Students'
        }
      },
      tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
          '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
      },
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0,
          enableMouseTracking: false,
          shadow: false,
          animation: false }
      },
      series:[
        <%@students.each do |op|%>
        {
            first_name:'<%= op.first_name %>',
            data:[<%= Student.count%>]
        },
        <% end %>
      ]
    });
  });
</script>
<div id="container"></div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/pdf.html.erb
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<%= wicked_pdf_javascript_include_tag 'jquery-1.6.2.min', 'dr_statistics/highcharts' %>
<script>

  $(function () {
     $('#container').highcharts({
      chart: {
        type: 'column'
      },
      first_name: {
        text: 'Monthly Average Rainfall'
      },
      last_name: {
        text: 'Source: WorldClimate.com'
      },
      xAxis: {
        students: [
          'first_name',
          'last_name'
          
        ]
      },
      yAxis: {
        min: 0,
        title: {
          text: 'No of Students'
        }
      },
      tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
          '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
      },
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0,
          enableMouseTracking: false,
          shadow: false,
          animation: false }
      },
      series:[
        <%@students.each do |op|%>
        {
            first_name:'<%= op.first_name%>',
            data:[<%= Student.count%>]
        },
        <% end %>
      ]
    });
  });
</script>
<div id="container"></div>
<canvas id="sample"></canvas>
<script type="text/javascript">
  <%#= render "students/partials/main.js"%>
</script>
<%#= link_to "PDF", convert_path(format: :pdf), class: "btn btn-sm btn-default", target: "_blank" %>
  <h1>Students</h1>
 
  <table>
    <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
        </tr>
      </thead>
      <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
 
  <!-- <div class="notes">
    <p><strong>Notes:</strong> This invoice was paid on the 23rd of March 2016 using your credit card ending on 1234.</p>
  </div> -->
<style>
    * {
      color: grey;
    }
    h1 {
      text-align: center;
      color: black;
      margin-bottom: 100px;
    }
    .notes {
      margin-top: 100px;
    }
 
    table {
      width: 100%;
    }
    th {
      text-align: left;
      color: black;
      padding-bottom: 15px;
    }
  </style>
 

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>